Repository sparta-PaletteGround/sparta-PaletteGround, pull requests merged in 2024-03, with the labels that each got.

#8 [feat]supabase.ts파일생성
  app/_utils/supabase/supabase.ts
Labels: documentation, enhancement

#18 [feat/#2] detail1 페이지 - supabase에서 post 데이터 가져오기
  app/_components/detail-1/Comments.tsx
  app/_components/detail-1/Drawing.tsx
  app/_components/detail-1/Painter.tsx
  app/_components/detail-api/detail-api.ts
  app/_types/detail1/posts.ts
  app/detail/[id]/page.tsx
  app/detail/page.tsx
Labels: enhancement

#26 Feat/mypage
  app/_components/myPageComponents/MypageNonAuth.tsx
  app/_components/myPageComponents/MypageUser.tsx
  app/_components/myPageComponents/modals/Modal.tsx
  app/_components/myPageComponents/myPageSupabase.ts
  app/_types/myPageType.ts
  app/mypage/page.tsx
Labels: documentation, enhancement

#48 [feat] 댓글 수정 구현
  app/_components/detail-1/Comments-Item.tsx
  app/_components/detail-1/Comments-list.tsx
  app/_components/detail-1/Comments.tsx
  app/_components/detail-api/comments-api.ts
  app/_types/detail1/comments.ts
Labels: enhancement

#49 Feat/mypage
  app/_components/myPageComponents/MypageUser.tsx
  app/_components/myPageComponents/myPageSupabase.ts
  package.json
  yarn.lock
Labels: bug, documentation, enhancement

#53 [feat] detail1 페이지 - 댓글 CRUD시 댓글수, 리스트 동시에 최신화
  app/_components/detail-1/Comments-Item.tsx
  app/_components/detail-1/Comments.tsx
  app/_components/detail-1/DrawingsByPainter.tsx
  app/_components/detail-1/Painter.tsx
  app/_components/detail-api/comments-api.ts
  app/_components/detail-api/painter-api.ts
  app/_components/myPageComponents/MypageUser.tsx
  app/_types/detail1/comments.ts
  app/detail/[id]/page.tsx
Labels: enhancement

#54 [feat] detail1 페이지 - 댓글 최신순 정렬, 유저가 그린 그림 css수정, 현재 그림 리스트에서 제외
  app/_components/detail-1/Comments-Item.tsx
  app/_components/detail-1/Comments-list.tsx
  app/_components/detail-1/Comments.tsx
  app/_components/detail-1/DrawingsByPainter.tsx
  app/_components/detail-api/painter-api.ts
Labels: enhancement

#60 [docs] 리드미 양식 업로드
  README.md
  app/_components/myPageComponents/MyPageLikeList.tsx
  app/_components/myPageComponents/MypageList.tsx
  app/_components/myPageComponents/myPageSupabase.ts
  app/mypage/page.tsx
Labels: documentation

#63 [feat] header - 프로필이미지 변경
  app/_api/getUsers.ts
  app/_components/detail-1/DrawingsByPainter.tsx
  app/_components/layout/header-loggedIn.tsx
  app/_components/layout/header.tsx
  app/layout.tsx
Labels: enhancement

#68 Feat/mypage
  app/_components/myPageComponents/MyPageMyWrite.tsx
  app/_components/myPageComponents/MypageList.tsx
  app/_components/myPageComponents/MypageUser.tsx
  app/_components/myPageComponents/myPageSupabase.ts
Labels: bug, documentation, enhancement

#73 [feat] 마이페이지 로그아웃시 메인페이지로 라우팅
  app/_components/myPageComponents/MyPageMyWrite.tsx
  app/_components/myPageComponents/MypageList.tsx
  app/_components/myPageComponents/MypageNonAuth.tsx
  app/_components/myPageComponents/MypageUser.tsx
  app/mypage/page.tsx
Labels: documentation, enhancement

#74 빌드 오류 해결
  app/_components/layout/header-loggedIn.tsx
  app/_components/myPageComponents/MyPageMyWrite.tsx
  app/_components/myPageComponents/MypageUser.tsx
  app/_components/paintEditor/Editor.tsx
  app/_types/detail1/comments.ts
  app/mypage/page.tsx
  app/paint-editor/page.tsx
  yarn.lock
Labels: bug, enhancement
